let g:coc_global_extensions = [
            \'coc-json',
            \'coc-css', 
            \'coc-cssmodules', 
            \'coc-diagnostic', 
            \'coc-emmet', 
            \'coc-eslint', 
            \'coc-html', 
            \'coc-prettier', 
            \'coc-snippets', 
            \'coc-tsserver', 
            \'coc-pairs', 
            \'coc-tailwindcss',
            \'coc-lua',
            \'coc-highlight']
